# Generated by Django 5.1 on 2024-08-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terminal',
            options={'verbose_name': 'My Terminal', 'verbose_name_plural': 'My Terminal'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='capacity',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='name',
            field=models.CharField(help_text='The terminal name should be less than 500 character', max_length=500, verbose_name='Terminal Name'),
        ),
    ]
